services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: mydb
    ports:
      - "33306:3306"
    volumes:
      - C:/docker-v-mysql:/var/lib/mysql
      - C:/docker-init:/docker-entrypoint-initdb.d
    networks:
      - my-net

  spring-boot-app:
    image: masterlee0210/with-study:${TAG}
    container_name: spring-app
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/mydb
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    depends_on:
      - mysql
    networks:
      - my-net

networks:
  my-net: